2024-12-11 23:43:26,412 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2024-12-11 23:43:26,413 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Configure stats pid to 495752
2024-12-11 23:43:26,413 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Loading settings from /home/ganesh/.config/wandb/settings
2024-12-11 23:43:26,413 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Loading settings from /mnt/ss/text_based_implementation/wandb/settings
2024-12-11 23:43:26,413 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-11 23:43:26,413 INFO    MainThread:495752 [wandb_init.py:_log_setup():528] Logging user logs to /mnt/ss/text_based_implementation/wandb/run-20241211_234326-drdvwcis/logs/debug.log
2024-12-11 23:43:26,413 INFO    MainThread:495752 [wandb_init.py:_log_setup():529] Logging internal logs to /mnt/ss/text_based_implementation/wandb/run-20241211_234326-drdvwcis/logs/debug-internal.log
2024-12-11 23:43:26,413 INFO    MainThread:495752 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9c00c036d0>
2024-12-11 23:43:26,414 INFO    MainThread:495752 [wandb_init.py:init():639] calling init triggers
2024-12-11 23:43:26,414 INFO    MainThread:495752 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {}
2024-12-11 23:43:26,414 INFO    MainThread:495752 [wandb_init.py:init():688] starting backend
2024-12-11 23:43:26,414 INFO    MainThread:495752 [wandb_init.py:init():692] sending inform_init request
2024-12-11 23:43:26,422 INFO    MainThread:495752 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-11 23:43:26,422 INFO    MainThread:495752 [wandb_init.py:init():705] backend started and connected
2024-12-11 23:43:26,424 INFO    MainThread:495752 [wandb_run.py:_label_probe_notebook():1327] probe notebook
2024-12-11 23:43:26,425 INFO    MainThread:495752 [wandb_run.py:_label_probe_notebook():1337] Unable to probe notebook: Expecting value: line 1 column 1 (char 0)
2024-12-11 23:43:26,425 INFO    MainThread:495752 [wandb_init.py:init():798] updated telemetry
2024-12-11 23:43:26,431 INFO    MainThread:495752 [wandb_init.py:init():830] communicating run to backend with 90.0 second timeout
2024-12-11 23:43:30,272 ERROR   MainThread:495752 [wandb_init.py:init():857] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your-username not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-11 23:43:30,273 ERROR   MainThread:495752 [wandb_init.py:init():1315] error in wandb.init()
Traceback (most recent call last):
  File "/home/ganesh/miniconda3/envs/senv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
  File "/home/ganesh/miniconda3/envs/senv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 863, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your-username not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-11 23:44:01,561 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2024-12-11 23:44:01,561 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Configure stats pid to 495752
2024-12-11 23:44:01,562 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Loading settings from /home/ganesh/.config/wandb/settings
2024-12-11 23:44:01,562 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Loading settings from /mnt/ss/text_based_implementation/wandb/settings
2024-12-11 23:44:01,562 INFO    MainThread:495752 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-11 23:44:01,562 INFO    MainThread:495752 [wandb_init.py:_log_setup():528] Logging user logs to /mnt/ss/text_based_implementation/wandb/run-20241211_234401-cr6gj614/logs/debug.log
2024-12-11 23:44:01,562 INFO    MainThread:495752 [wandb_init.py:_log_setup():529] Logging internal logs to /mnt/ss/text_based_implementation/wandb/run-20241211_234401-cr6gj614/logs/debug-internal.log
2024-12-11 23:44:01,562 INFO    MainThread:495752 [wandb_init.py:init():639] calling init triggers
2024-12-11 23:44:01,562 INFO    MainThread:495752 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {}
2024-12-11 23:44:01,562 INFO    MainThread:495752 [wandb_init.py:init():688] starting backend
2024-12-11 23:44:01,563 INFO    MainThread:495752 [wandb_init.py:init():692] sending inform_init request
2024-12-11 23:44:01,569 INFO    MainThread:495752 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-11 23:44:01,570 INFO    MainThread:495752 [wandb_init.py:init():705] backend started and connected
2024-12-11 23:44:01,572 INFO    MainThread:495752 [wandb_run.py:_label_probe_notebook():1327] probe notebook
2024-12-11 23:44:01,572 INFO    MainThread:495752 [wandb_run.py:_label_probe_notebook():1337] Unable to probe notebook: Expecting value: line 1 column 1 (char 0)
2024-12-11 23:44:01,572 INFO    MainThread:495752 [wandb_init.py:init():798] updated telemetry
2024-12-11 23:44:01,579 INFO    MainThread:495752 [wandb_init.py:init():830] communicating run to backend with 90.0 second timeout
2024-12-11 23:44:02,095 INFO    MainThread:495752 [wandb_init.py:init():882] starting run threads in backend
2024-12-11 23:44:32,310 INFO    MainThread:495752 [wandb_run.py:_console_start():2443] atexit reg
2024-12-11 23:44:32,310 INFO    MainThread:495752 [wandb_run.py:_redirect():2293] redirect: wrap_raw
2024-12-11 23:44:32,310 INFO    MainThread:495752 [wandb_run.py:_redirect():2358] Wrapping output streams.
2024-12-11 23:44:32,310 INFO    MainThread:495752 [wandb_run.py:_redirect():2383] Redirects installed.
2024-12-11 23:44:32,312 INFO    MainThread:495752 [wandb_init.py:init():925] run started, returning control to user process
